### PR TITLE
Filter discovery messages against HASS classes list

### LINKED ISSUE #1123: Mi Body Composition Scale2 discovery XMTZC05HM not working in 0.9.9beta
Mi XMTZC05HM Mi Body Composition Scale2 FW vers 1.0.0.12

This scale works okay with the Mi Fit Android app and was recognized in OMG v0.9.6.

With v0.9.6, in MQTT Explorer:
  (I don't know how to keep the formatting & indentation when copying from MQTT Explorer)

> homeassistant/sensor/0C9541AD7717-MiScale-weight/config
{"stat_t":"+/+/BTtoMQTT/0C9541AD7717",
"name":"MiScale-weight",
"uniq_id":"0C9541AD7717-MiScale-weight",
"val_tpl":"{{ value_json.weight | is_defined }}",
"unit_of_meas":"kg",
"device":{
 "connections":[
   ["mac",
    "0C9541AD7717"]
   ],
  "identifiers":[
    "0C9541AD7717"
   ],
  "manufacturer":"Xiaomi",
  "model":"XMTZC0xHM",
  "name":"MiScale",
  "via_device":"OMG_ESP32_CUSTOM_BT"
  }
}

> home/OMG_ESP32_CUSTOM_BT/BTtoMQTT/0C9541AD7717
{
  "id":"0C:95:41:AD:77:17",
  "name":"MIBFS",
  "manufacturerdata":"57010c9541ad7717",
  "rssi":-71,
  "model":"XMTZC05HM",
  "weight":4.35,
  "impedance":0
}

In Home Assistant, Device info shows XMTZC0xHM by Xiaomi and a MIScale-weight sensor is created as expected.

But with v0.9.9beta, in MQTT Explorer:

There is no config topic for the Mi scale but there are for other BLE devices.

> home/OMG_ESP32_CUSTOM_BT/BTtoMQTT/0C9541AD7717
{
  "id":"0C:95:41:AD:77:17",
  "name":"MIBFS",
  "manufacturerdata":"57010c9541ad7717",
  "rssi":-76,
  "servicedata":"0384e5070c170c301d00006603"
}

Other BLE devices work okay in v0.9.9beta.

Could it be that this scale identifies itself with the name MIBFS unlike other Mi scales?

### PR DESCRIPTION
**Pull request by 1technophile**
## Description:
fix #1123 

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] I accept the [DCO](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

File: main/config_mqttDiscovery.h [hunk 1]
```diff
@@ -196,4 +196,8 @@ void announceDeviceTrigger(bool use_gateway_info,
 #  define stateClassTotalIncreasing "total_increasing"
 #endif
 
+// From https://github.com/home-assistant/core/blob/d7ac4bd65379e11461c7ce0893d3533d8d8b8cbf/homeassistant/const.py#L225
+// List of classes available in Home Assistant
+const char* availableHASSClasses[14] = {"battery", "carbon_monoxide", "carbon_dioxide", "humidity", "illuminance", "signal_strength", "temperature", "timestamp", "pressure", "power", "current", "energy", "power_factor", "voltage"};
```
Comment (h2zero) [inline main/config_mqttDiscovery.h]: I'd suggest removing the fixed array size value and just have empty braces and put the items on a separate line for each to make this more maintainable for future additions. Disregard this if that is not expected.

File: main/ZmqttDiscovery.ino [hunk 2]
```diff
@@ -245,19 +245,27 @@ void createDiscovery(const char* sensor_type,
     sensor["stat_t"] = state_topic;
   }
 
+  // We check if the class belongs to HAAS class list
+  bool HASSClass = false;
+  for (int i = 0; i < 14; i++) { // see class list and size into config_mqttDiscovery.h
```
Comment (h2zero) [inline main/ZmqttDiscovery.ino]: If the change mentioned to the array definition is accepted this will need to be changed to accommodate it to:
```
int num_classes = sizeof(availableHASSClasses) / sizeof(availableHASSClasses[0]);
for (int i = 0; i < num_classes; i++) {
```

**Review by h2zero — APPROVED** [review]
Looks good to me, just a minor suggestion but not necessary. I'll leave it to your discretion.
